services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pruebaconcepto-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Captavale123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: pruebaconcepto-rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: edgar
      RABBITMQ_DEFAULT_PASS: 12341234a
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  sqlserver-data:
  rabbitmq-data: